micronaut:
  application:
    name: gabriel
grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    pix:
      address: 'localhost:50051'
      plaintext: true
      max-retry-attempts: 10

jackson:
  serialization:
    writeDatesAsTimestamps: false


